FROM alpine:3.13

ARG TERRAFORM_DEFAULT_VERSION=1.6.4
ARG JQ_VERSION=1.7
ARG YQ_VERSION=v4.35.2
ARG TFCMT_VERSION=v4.7.1
ARG GITHUBCOMMENT_VERSION=6.0.2
ARG QBCONF_VERSION=1.0.0

RUN apk add --update --no-cache curl ca-certificates bash libc6-compat


# Install jq
RUN curl -sLO https://github.com/stedolan/jq/releases/download/jq-${JQ_VERSION}/jq-linux64 && \
    mv jq-linux64 /usr/local/bin/jq && \
    chmod +x /usr/local/bin/jq

# Install qbconf
RUN curl -sSL https://github.com/RaftechNL/qbconf/releases/download/${QBCONF_VERSION}/qbconf_linux_amd64.tar.gz | tar -xz && \
    mv qbconf_linux_amd64 /usr/local/bin/qbconf

# Install yq 4.33.3
COPY --from=mikefarah/yq@sha256:11da99074a0a985650669ab49b392733a8439bf31291e64aa6d012f7a5d98dfd /usr/bin/yq /usr/bin/yq

# Install gomplate
COPY --from=hairyhenderson/gomplate:stable /gomplate /bin/gomplate

# Install tfcmt
RUN curl -sSL  https://github.com/suzuki-shunsuke/tfcmt/releases/download/${TFCMT_VERSION}/tfcmt_linux_amd64.tar.gz | tar xvz -C /tmp \
      && mv /tmp/tfcmt usr/local/bin/tfcmt \
      && chmod +x /usr/local/bin/tfcmt

RUN curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | sh && /usr/local/bin/tfswitch -d $TERRAFORM_DEFAULT_VERSION

RUN curl -L https://github.com/suzuki-shunsuke/github-comment/releases/download/v${GITHUBCOMMENT_VERSION}/github-comment_${GITHUBCOMMENT_VERSION}_linux_amd64.tar.gz | tar xvz -C /tmp \
      && mv /tmp/github-comment /usr/local/bin/github-comment \
      && chmod +x /usr/local/bin/github-comment

ENTRYPOINT ["/bin/bash"]