name: build-containers

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write # required for OIDC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "cicd:inject-slug-variables"
        uses: rlespinasse/github-slug-action@v4
        with:
          prefix: CI_

      - name: "aws:configure-credentials"
        uses: aws-actions/configure-aws-credentials@v1
        id: aws-credentials
        with:
          role-to-assume: "arn:aws:iam::${{ secrets.RAFTECH_AWS_ACCOUNT_ID }}:role/GithubActionsRole"
          role-session-name: "raftech-public-ecr-gha"
          aws-region: "us-east-1"
          mask-aws-account-id: no

      - name: "aws:login-to-ecr"
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: "public"

      - name: "docker:setup-metadata"
        id: metadata
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/p8o7f1g4/platform
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: "kaniko:build-and-push-image"
        uses: int128/kaniko-action@v1.14.0
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache: false
          context: "./platform/aws-cli-v2"
